# Form implementation generated from reading ui file 'Importar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Importar(object):
    def setupUi(self, Importar):
        Importar.setObjectName("Importar")
        Importar.resize(480, 548)
        Importar.setMinimumSize(QtCore.QSize(480, 548))
        self.frame = QtWidgets.QFrame(parent=Importar)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 541))
        self.frame.setMinimumSize(QtCore.QSize(480, 540))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("""
            background-color: #222;
            border-radius: 10px;
        """)
        self.pushButtonCargarLyrics = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonCargarLyrics.setGeometry(QtCore.QRect(170, 490, 131, 31))
        self.pushButtonCargarLyrics.setObjectName("pushButtonCargarLyrics")
        self.pushButtonCargarLyrics.setStyleSheet("""
            QPushButton {
                background-color: #333;
                color: #FFF;
                font: bold 10pt "Segoe UI";
                border: 1px solid #555;
                border-radius: 5px;
                padding: 5px;
            }
            QPushButton:hover {
                background-color: #444;
                border: 1px solid #888;
            }
            QPushButton:pressed {
                background-color: #222;
                border: 1px solid #222;
            }
        """)
        self.textEditLyricsSet = QtWidgets.QTextEdit(parent=self.frame)
        self.textEditLyricsSet.setGeometry(QtCore.QRect(10, 10, 461, 471))
        self.textEditLyricsSet.setObjectName("textEditLyricsSet")
        self.textEditLyricsSet.setStyleSheet("""
            color: #FFF;
            font: 10pt "Segoe UI";
            background-color: #333;
            border: 1px solid #444;
            border-radius: 10px;
        """)

        self.retranslateUi(Importar)
        QtCore.QMetaObject.connectSlotsByName(Importar)

    def retranslateUi(self, Importar):
        _translate = QtCore.QCoreApplication.translate
        Importar.setWindowTitle(_translate("Importar", "Dialog"))
        self.pushButtonCargarLyrics.setText(_translate("Importar", "Cargar Lyrics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Importar = QtWidgets.QDialog()
    ui = Ui_Importar()
    ui.setupUi(Importar)
    Importar.show()
    sys.exit(app.exec())
